version: "3"

services:
  membrane-live-db:
    container_name: membrane_live_db
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-membrane}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB:-live_db}"
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${POSTGRES_DB:-live_db}",
          "-U",
          "${POSTGRES_USER:-membrane}"
        ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  membrane-live:
    image: membraneframeworklabs/membrane_live:${TAG:-latest}
    container_name: membrane_live
    network_mode: "host"
    # build: .
    depends_on:
      - membrane-live-db
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-membrane}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB:-live_db}"
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      VIRTUAL_HOST: "${VIRTUAL_HOST:-localhost}"
      USE_INTEGRATED_TURN: "true"
      INTEGRATED_TURN_IP: "${INTEGRATED_TURN_IP:-127.0.0.1}"
      INTEGRATED_TURN_PORT_RANGE: "50000-65355"
      INTEGRATED_TCP_TURN_PORT: "49999"

volumes:
  pgdata:
