version: "3"

services:
  membrane-live-db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  membrane-live:
    container_name: membrane_live
    network_mode: "host"
    build: .
    depends_on:
      - membrane-live-db
    environment:
      PGUSER: "${POSTGRES_USER}"
      PGPASSWORD: "${POSTGRES_PASSWORD}"
      PGDATABASE: "${POSTGRES_DB}"
      PGHOST: localhost
      PGPORT: 5432
      VIRTUAL_HOST: "${VIRTUAL_HOST:-localhost}"
      USE_INTEGRATED_TURN: "true"
      INTEGRATED_TURN_IP: "${INTEGRATED_TURN_IP:-127.0.0.1}"
      INTEGRATED_TURN_PORT_RANGE: "50000-65355"
      INTEGRATED_TCP_TURN_PORT: "49999"

volumes:
  pgdata:
